# based on https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/appveyor.yml

# build version
version: '{build}'

# Do not build on tags
skip_tags: true

# enviroment settings
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.6.0
      M2_HOME: C:\bin\apache-maven-3.2.5
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
      MAVEN_OPTS: -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

matrix:
  allow_failures:
    - JAVA_HOME: C:\Program Files\Java\jdk1.6.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0

# install required tools (maven, secure-file, encrypted files)
install:
  - cmd: if not exist "C:\bin\apache-maven-3.2.5\bin\*.*" cinst maven --version 3.2.5 --allow-empty-checksums
  - cmd: echo %JAVA_HOME%
  - cmd: echo %M2_HOME%

# build and install artifacts
build_script:
  - '"%M2_HOME%\bin\mvn" clean install -DskipTests'

# verify artifacts
test_script:
  - '"%M2_HOME%\bin\mvn" test'

# preserve dependencies between builds
cache:
  - C:\Users\appveyor\.m2
  - C:\bin\apache-maven-3.2.5
